export const fontImport = `
@import url('https://fonts.googleapis.com/css2?family=Anton&family=Space+Mono:wght@400;700&family=Inter:wght@400;500;600;700&display=swap');
:root {
  --ink: #16241F;
  --court: #1F5C43;
  --court-dark: #163F2E;
  --chalk: #F3F1E4;
  --ball: #D4E157;
  --coral: #E85D4C;
  --line: #C9C4AE;
}
`;

export const styles = {
  app: {
    fontFamily: "'Inter', sans-serif",
    background: "var(--chalk)",
    color: "var(--ink)",
    minHeight: "100%",
    borderRadius: 12,
    overflow: "hidden",
  },
  landingWrap: {
    padding: "40px 24px",
    maxWidth: 640,
    margin: "0 auto",
  },
  landingHero: {
    textAlign: "center",
    marginBottom: 28,
  },
  landingTitle: {
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontSize: "clamp(26px, 5vw, 38px)",
    textTransform: "uppercase",
    margin: "6px 0 10px 0",
    color: "var(--court)",
    lineHeight: 1.05,
  },
  landingSub: {
    fontSize: 14,
    color: "#5c6157",
    maxWidth: 420,
    margin: "0 auto",
  },
  landingCards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 16,
  },
  landingCard: {
    background: "#fff",
    border: "1.5px solid var(--line)",
    borderRadius: 12,
    padding: 20,
  },
  landingCardTitle: {
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontSize: 17,
    textTransform: "uppercase",
    margin: "0 0 6px 0",
  },
  landingCardText: {
    fontSize: 12.5,
    color: "#6b7268",
    margin: "0 0 14px 0",
    lineHeight: 1.5,
  },
  codeInput: {
    fontFamily: "'Space Mono', monospace",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    textAlign: "center",
  },
  adminLink: {
    display: "block",
    margin: "26px auto 0 auto",
    background: "none",
    border: "none",
    color: "#8a8f83",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "center",
  },
  adminCode: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.05em",
  },
  createWrap: {
    padding: "22px 24px 30px 24px",
    maxWidth: 520,
    margin: "0 auto",
  },
  backBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "none",
    border: "none",
    color: "#6b7268",
    fontSize: 12.5,
    fontWeight: 700,
    cursor: "pointer",
    padding: 0,
    marginBottom: 18,
  },
  courtStepper: {
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  courtStepperCount: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 22,
    fontWeight: 700,
    minWidth: 20,
    textAlign: "center",
  },
  rosterList: {
    listStyle: "none",
    padding: 0,
    margin: "4px 0 4px 0",
    maxWidth: 480,
  },
  rosterItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 0",
    borderBottom: "1px solid var(--line)",
    fontSize: 13.5,
  },
  rosterRemoveBtn: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "var(--chalk)",
    color: "#8a8f83",
    border: "1px solid var(--line)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    marginLeft: "auto",
    padding: 0,
  },
  checkInTapBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginLeft: "auto",
    background: "var(--court)",
    color: "var(--chalk)",
    border: "none",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    flexShrink: 0,
  },
  startBtn: {
    width: "100%",
    justifyContent: "center",
    marginTop: 22,
    padding: "13px 0",
    fontSize: 14,
  },
  header: {
    background: "var(--court)",
    color: "var(--chalk)",
    padding: "20px 24px 0 24px",
  },
  headerInner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    flexWrap: "wrap",
    gap: 12,
    paddingBottom: 16,
  },
  kicker: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.14em",
    color: "var(--ball)",
    marginBottom: 6,
    fontWeight: 700,
  },
  title: {
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontSize: "clamp(22px, 4vw, 32px)",
    letterSpacing: "0.01em",
    margin: 0,
    lineHeight: 1.05,
    textTransform: "uppercase",
  },
  headerStats: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    alignItems: "center",
  },
  statPill: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(243,241,228,0.12)",
    border: "1px solid rgba(243,241,228,0.25)",
    borderRadius: 999,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 600,
  },
  codePill: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "var(--ball)",
    color: "var(--ink)",
    border: "none",
    borderRadius: 999,
    padding: "6px 12px",
    fontSize: 11.5,
    fontWeight: 700,
    fontFamily: "'Space Mono', monospace",
    cursor: "pointer",
    letterSpacing: "0.04em",
  },
  leaveBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    borderRadius: "50%",
    background: "rgba(243,241,228,0.12)",
    border: "1px solid rgba(243,241,228,0.25)",
    color: "var(--chalk)",
    cursor: "pointer",
  },
  dot: (active) => ({
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: active ? "var(--ball)" : "var(--coral)",
    display: "inline-block",
  }),
  nav: {
    display: "flex",
    gap: 4,
  },
  navBtn: {
    background: "transparent",
    border: "none",
    color: "rgba(243,241,228,0.65)",
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.03em",
    cursor: "pointer",
    borderBottom: "3px solid transparent",
    fontFamily: "'Inter', sans-serif",
  },
  navBtnActive: {
    color: "var(--chalk)",
    borderBottom: "3px solid var(--ball)",
  },
  kitchenLine: {
    height: 0,
    borderTop: "2px dashed var(--line)",
    background: "var(--chalk)",
  },
  main: {
    padding: "22px 24px 8px 24px",
    minHeight: 320,
  },
  loading: {
    padding: 40,
    textAlign: "center",
    color: "#6b7268",
    fontSize: 14,
  },
  sectionLabel: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.12em",
    color: "#6b7268",
    margin: "22px 0 10px 0",
    textTransform: "uppercase",
  },
  courtGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 14,
  },
  courtCard: (status) => ({
    background: "#fff",
    border: `1.5px solid ${status === "finished" ? "var(--coral)" : "var(--line)"}`,
    borderRadius: 10,
    padding: 16,
    position: "relative",
  }),
  courtHeadRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  courtBadge: {
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontSize: 12,
    letterSpacing: "0.06em",
    background: "var(--ink)",
    color: "var(--chalk)",
    padding: "3px 8px",
    borderRadius: 4,
  },
  statusTag: (status) => ({
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.08em",
    color:
      status === "open" ? "#6b7268" : status === "finished" ? "var(--coral)" : "var(--court)",
  }),
  openCourtBody: {
    textAlign: "center",
    padding: "14px 0 6px 0",
  },
  openCourtText: {
    color: "#8a8f83",
    fontSize: 13,
    margin: "0 0 12px 0",
  },
  teamRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6px 0",
    gap: 8,
  },
  teamPlayers: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
  },
  playerChip: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  subBtn: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    border: "1px solid var(--line)",
    background: "var(--chalk)",
    color: "#8a8f83",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    padding: 0,
  },
  subReturnLabel: {
    fontSize: 12,
    color: "#5c6157",
    margin: "10px 0 0 0",
  },
  teamName: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "#5c6157",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  avatarImg: {
    borderRadius: "50%",
    objectFit: "cover",
    border: "1.5px solid #fff",
    boxShadow: "0 0 0 1px var(--line)",
    flexShrink: 0,
  },
  avatarInitials: {
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontSize: 10,
    flexShrink: 0,
    border: "1.5px solid #fff",
    boxShadow: "0 0 0 1px var(--line)",
  },
  photoRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  photoPreviewWrap: {
    position: "relative",
    width: 52,
    height: 52,
  },
  photoPreview: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    objectFit: "cover",
    border: "1.5px solid var(--line)",
  },
  photoPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "#fff",
    border: "1.5px dashed var(--line)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  photoClearBtn: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: "50%",
    background: "var(--coral)",
    color: "#fff",
    border: "1.5px solid var(--chalk)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  photoLabel: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--court)",
    cursor: "pointer",
    textDecoration: "underline",
    textUnderlineOffset: 3,
  },
  scoreControl: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  scoreBtn: {
    width: 24,
    height: 24,
    borderRadius: 6,
    border: "1.5px solid var(--line)",
    background: "var(--chalk)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "var(--ink)",
  },
  scoreDigit: {
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontSize: 22,
    minWidth: 28,
    textAlign: "center",
  },
  vsLine: {
    borderTop: "1.5px dashed var(--line)",
    margin: "2px 0",
  },
  courtActionsRow: {
    display: "flex",
    gap: 8,
    marginTop: 14,
  },
  fixTeamsBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: "#fff",
    color: "#5c6157",
    border: "1.5px solid var(--line)",
    borderRadius: 7,
    padding: "9px 12px",
    fontWeight: 700,
    fontSize: 11.5,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  editHint: {
    fontSize: 12,
    color: "#8a8f83",
    margin: "0 0 10px 0",
  },
  editGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  editChip: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 8,
    border: "1.5px solid var(--line)",
    background: "#fff",
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "'Inter', sans-serif",
  },
  editChipA: {
    borderColor: "var(--court)",
    background: "rgba(31,92,67,0.06)",
  },
  editChipB: {
    borderColor: "var(--coral)",
    background: "rgba(232,93,76,0.06)",
  },
  editChipName: {
    flex: 1,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--ink)",
  },
  editChipSide: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    fontWeight: 700,
    color: "#8a8f83",
  },
  editWarning: {
    fontSize: 11.5,
    color: "var(--coral)",
    fontWeight: 600,
    margin: "8px 0 0 0",
  },
  editActions: {
    display: "flex",
    gap: 8,
    marginTop: 12,
  },
  standingsTable: {
    maxWidth: 480,
  },
  standingsHeadRow: {
    display: "flex",
    alignItems: "center",
    padding: "6px 0",
    borderBottom: "2px solid var(--ink)",
    fontFamily: "'Space Mono', monospace",
    fontSize: 10.5,
    fontWeight: 700,
    color: "#8a8f83",
    letterSpacing: "0.06em",
  },
  standingsRow: {
    display: "flex",
    alignItems: "center",
    padding: "9px 0",
    borderBottom: "1px solid var(--line)",
  },
  standingsRankCol: {
    width: 24,
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    color: "#8a8f83",
  },
  standingsNameCol: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  standingsName: {
    fontSize: 13.5,
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  standingsStatCol: {
    width: 36,
    textAlign: "center",
    fontFamily: "'Space Mono', monospace",
    fontSize: 13,
    fontWeight: 600,
  },
  standingsNote: {
    fontSize: 11.5,
    color: "#a3a89a",
    marginTop: 14,
  },
  endMatchBtn: {
    flex: 1,
    background: "var(--ball)",
    color: "var(--ink)",
    border: "none",
    borderRadius: 7,
    padding: "9px 0",
    fontWeight: 700,
    fontSize: 12.5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    cursor: "pointer",
  },
  checkinWrap: { maxWidth: 480 },
  checkinRow: { display: "flex", gap: 8 },
  input: {
    flex: 1,
    padding: "11px 14px",
    borderRadius: 8,
    border: "1.5px solid var(--line)",
    fontSize: 14,
    fontFamily: "'Inter', sans-serif",
    background: "#fff",
    color: "var(--ink)",
  },
  primaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "var(--court)",
    color: "var(--chalk)",
    border: "none",
    borderRadius: 8,
    padding: "11px 16px",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  dangerBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "var(--coral)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "9px 14px",
    fontWeight: 700,
    fontSize: 12.5,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  secondaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    margin: "0 auto",
    background: "var(--chalk)",
    color: "var(--ink)",
    border: "1.5px solid var(--ink)",
    borderRadius: 7,
    padding: "8px 14px",
    fontWeight: 700,
    fontSize: 12.5,
    cursor: "pointer",
  },
  btnDisabled: { opacity: 0.4, cursor: "not-allowed" },
  confirmMsg: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: "var(--court)",
    fontSize: 13,
    fontWeight: 600,
    marginTop: 10,
  },
  queueList: { listStyle: "none", padding: 0, margin: 0, maxWidth: 480 },
  queueItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 0",
    borderBottom: "1px solid var(--line)",
    fontSize: 13.5,
  },
  queueNum: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    color: "#8a8f83",
    width: 16,
  },
  queueName: { flex: 1, fontWeight: 600 },
  resultTag: (result) => ({
    fontFamily: "'Space Mono', monospace",
    fontSize: 10,
    fontWeight: 700,
    color: "#fff",
    background: result === "win" ? "var(--court)" : "var(--coral)",
    borderRadius: 4,
    padding: "2px 5px",
    flexShrink: 0,
  }),
  queueGames: { fontSize: 11, color: "#8a8f83" },
  matchupCard: (isNext) => ({
    background: "#fff",
    border: `1.5px solid ${isNext ? "var(--court)" : "var(--line)"}`,
    borderRadius: 10,
    padding: "12px 14px",
    marginBottom: 10,
  }),
  matchupHeader: (isNext) => ({
    fontFamily: "'Space Mono', monospace",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: isNext ? "var(--court)" : "#8a8f83",
    marginBottom: 9,
    textTransform: "uppercase",
  }),
  matchupTeams: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  matchupTeam: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  },
  matchupVs: {
    fontFamily: "'Anton', sans-serif",
    fontSize: 12,
    color: "var(--coral)",
    flexShrink: 0,
  },
  emptyQueue: { color: "#8a8f83", fontSize: 13.5 },
  loginWrap: {
    maxWidth: 340,
    margin: "20px auto",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
  },
  loginTitle: {
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontSize: 20,
    textTransform: "uppercase",
    margin: "10px 0 2px 0",
  },
  loginSub: { fontSize: 13, color: "#6b7268", margin: "0 0 12px 0" },
  pinInput: {
    width: "100%",
    textAlign: "center",
    letterSpacing: "0.3em",
    fontSize: 18,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1.5px solid var(--line)",
    marginBottom: 10,
    fontFamily: "'Space Mono', monospace",
  },
  pinError: { color: "var(--coral)", fontSize: 12.5, marginTop: 8, fontWeight: 600 },
  loginNote: { fontSize: 11.5, color: "#a3a89a", marginTop: 14 },
  scorerToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    flexWrap: "wrap",
    gap: 10,
  },
  toolbarText: { fontSize: 13.5, color: "#5c6157" },
  syncError: {
    marginTop: 16,
    fontSize: 12,
    color: "var(--coral)",
    fontWeight: 600,
  },
  footer: {
    textAlign: "center",
    fontSize: 11,
    color: "#a3a89a",
    padding: "14px 0 18px 0",
  },
};
